name: Alerta de Push a Main

on:
  push:
    branches:
      - main

jobs:
  notificar:
    name: Enviar Notificación a ntfy.sh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Ejecutar Hola Mundo
        run: node hola-mundo.js

      - name: Enviar notificación a ntfy.sh
        run: |
          curl -X POST https://ntfy.sh/devops-itla \
            -H "Title: ✅ Nuevo Push Detectado" \
            -H "Priority: high" \
            -H "Tags: rocket,github" \
            -d "🚀 Push en main. Autor: ${{ github.actor }} | Commit: ${{ github.sha }}"